'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
const total=59
const modules=[['01','THE MINDSET',7,'/curriculum#module-01'],['02','MASTER AI',8,'/curriculum#module-02'],['03','FIND THE BUSINESS',7,'/curriculum#module-03'],['04','BUILD',7,'/curriculum#module-04'],['05','SELL',8,'/curriculum#module-05'],['06','BUILD THE MACHINE',6,'/curriculum#module-06'],['07','SCALE',6,'/curriculum#module-07'],['08','THE PERSON BEHIND THE BUSINESS',10,'/curriculum#module-08']]
export default function Dashboard(){
 const[done,setDone]=useState<string[]>([])
 useEffect(()=>{const current=JSON.parse(localStorage.getItem('aisys_completed')||localStorage.getItem('a i s y s_completed')||'[]');setDone(current)},[])
 const pct=Math.round(done.length/total*100)
 const moduleProgress=(href:string)=>{const map:Record<string,string>={'/curriculum#module-01':'01','/curriculum#module-02':'02','/curriculum#module-03':'03','/curriculum#module-04':'04','/curriculum#module-05':'05','/curriculum#module-06':'06','/curriculum#module-07':'07','/curriculum#module-08':'08'};const prefix=map[href];if(!prefix)return 0;const names=[['Money follows value','Income vs. wealth','Skills vs. shortcuts','Why people pay','Finding expensive problems','Opportunity vs. hype','The 10-problem challenge'],['What AI actually does','Context is the multiplier','Prompt architecture','Research without getting fooled','AI writing and analysis','Multimodal AI','Automation and agents','Build your personal AI operating system'],['Problem discovery','Customer discovery','Pain and urgency','Competitor intelligence','Market size and signal','Offer hypotheses','48-hour validation'],['Choose the right build path','AI service offers','Digital products','Prototypes and MVPs','No-code and code','User feedback loops','Ship before perfect'],['Positioning','Craft the offer','Pricing','Outreach','Content that earns attention','Sales conversations','Objections and follow-up','First customer challenge'],['Map the workflow','SOPs','Lead tracking','Customer operations','AI automations','The owner dashboard'],['Know your numbers','Retention','Delegation','Hiring vs. automation','Reinvestment','Scale without chaos'],['Nobody is coming','Love being a beginner','Rejection is information','Stop comparing chapter 1 to chapter 20','Discipline when motivation disappears','Your reputation is an asset','Do not let lifestyle eat your future','Looking rich vs. becoming wealthy','Build something you would be proud to own','When you finally believe you can']];const i=Number(prefix)-1;const count=names[i].filter(x=>done.includes(x.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''))).length;return Math.round(count/names[i].length*100)}
 return <div className="shell dash"><nav className="nav"><Link className="brand" href="/">AI IS YOUR SUPERPOWER<span>.</span></Link><div className="navlinks"><Link href="/curriculum">Curriculum</Link><Link href="/journal">Journal</Link><Link href="/capstone">Capstone</Link></div></nav>
 <main className="dashHero"><div className="eyebrow">YOUR BUILD ROOM</div><h1>Stop collecting information.<br/><em>Start creating evidence.</em></h1><p className="lead muted">One lesson. One action. One step closer to something real.</p>
 <div className="stats"><div className="stat"><strong>{pct}%</strong><span className="muted">course progress</span><div className="progressbar"><i style={{width:pct+'%'}}/></div></div><div className="stat"><strong>{done.length}</strong><span className="muted">lessons completed</span></div><div className="stat"><strong>{total-done.length}</strong><span className="muted">lessons remaining</span></div></div>
 <div className="card"><div className="eyebrow">START HERE</div><h2>Money follows value.</h2><p className="muted">Before tools, tactics and technology, learn how customers decide what is worth paying for.</p><Link className="btn" href="/lesson/money-follows-value">Open lesson →</Link></div>
 <section className="section"><div className="eyebrow">YOUR PATH</div><h2>Build. Sell. Scale.</h2><div className="grid">{modules.map(([n,t,count,href])=><Link className="card" href={href as string} key={n}><div className="eyebrow">MODULE {n} · {count} LESSONS</div><h3>{t}</h3><div className="progressbar"><i style={{width:moduleProgress(href as string)+'%'}}/></div><p className="muted">Open module →</p></Link>)}</div></section>
 <section className="section"><div className="eyebrow">FINAL PROJECT</div><h2>Build something you can show.</h2><p className="muted">Your capstone turns the course into a real business blueprint: evidence, decisions and next actions.</p><Link className="btn" href="/capstone">Open the capstone →</Link></section>
 </main></div>
}